language: node_js
node_js:
    - stable

cache:
    directories:
        - node_modules

branches:
    only:
        - master

install:
    - npm install

jobs:
    include:
        - stage: test
          script: 'npm run test && node_modules/codecov/bin/codecov'
        - stage: docs
          script: 'npm run docs && node scripts/deployDocs.js'

env:
    global:
        - GITHUB_REPO: 'algrx/algorithmx'
        # GITHUB_TOKEN
        - secure: 'lepsZsMFCz5kx5L09HTFA1tyKy3SpsuKux8aJq8gmWPHLAEi4s+ODy594q5nVCD1KUFsJO1aw9ZHMlMK3x2USUiWUv3OttnDcNmvZVCAoaZIa6AMndLL3nYgKDDjx8uRJSdLA0rdCwiluwjnK/ej8fb1684z96HErEjT+jcxMlRdoDxf+WU1sjJ5lcZN9pUfFOiPzG6hH370r3Od1RoYtf8Y1P7wDc0Lm8AiVYMIWnzPl2KjoKrWbvjRw7O3/EDNH9CKHLlwFCYai7VyQGtHvf+kiJhBYdq5abo/YU0eA6YiBh2aZW5wlxew//yY2/+oXXp4oREwAa91IQcdBrh3If4XvgWkG4Zr8/FZhdzDgn2aXTpxBw7ldXgUilW83Ol8GmfaPwmhuzyZAMUHM/yv4YdfozPE8phHY30lyh1fdVCX/Fi9GU2S0u2tTf355Gjqib0/Y2cVsM5TlU82GtdFHkTUz6MsUNaH4C/ZoROBAfAzO+AMPuhSndiQBphctdjw2tr/8GA//grw/uGvp7Mkr0T1QxUJmZf99LiK7cgHTPW9iu1XJxUYuwRdlljMtU1FJJ7FJKpMwed8Q2T9hdwZPg7fOoG6eVYwH7AxIxNcky6vdD8Tyc+tlDvmJes6Jg460Pp+7z+97d9nLvRKHJeKbGNH00dlqtDJopspTQPPMmU='
