language: node_js
node_js:
- stable

cache:
  directories:
  - node_modules

branches:
  only:
  - master

install:
- npm install

jobs:
  include:
  - stage: test
    script: "npm run test && node_modules/codecov/bin/codecov"
  - stage: docs
    script: "npm run docs && node scripts/deployDocs.js"

env:
  global:
  - GITHUB_REPO: "algrx/algorithmx"
  # GITHUB_TOKEN
  - secure: "cOyYqSDoJzApl9c711ZXtqq657xpmbdqbOEFFgs5jJJl5MhrEUMPyul6CBIqqtgjlI3rU98vO15mWx/sBwkW2cnwvUnTtz+pnFT7RNksOnTh3WMJOC1IGkX2Q++8eZypkUJG9OAdP8qSfx98pJygXaLKPzujQb6oA6MyALZj6Wr7X5APALUMzeWNG+n73gcAyD881RwXIZK1+0qR8YAylIqwlqUfZGYSnXR9eA3dn/J992uSG+ruMKaJeIctIn+2CKNnJPpZCSohh1I0jMlyZPAZ33rnloDmAO2OZdKE0TB0PjwYVyrg1SPkQr9i7vokQAZ/HTbBcnyhx7e+rZbCsU16VlLMVNWUcAjHdPfK9f8cj/b/sRIMTaq8a/Zwja6CS0NLxH7ZdBhRlexxmYgLhHZG172WTQaVhigaN+0FgulhHsgtZ1suDDyBgUwdNNXXPungtHQoMOvPR8c21MpKcWNYBR76D8sMI97aCEUtvnuyX4G86iTXc6OMvjRVOKVLBJvn25HaInjjsIANwIPs8CdRGJZnKNaARCtZ/VcXbHlTiHo9m/v1zlbjcZ2Y8NrvLgRvNw/K9/bIQctaTXW4Gt8ZZU6nL8I3hOR2I+V+08Pm4VX2ovaT8xy3HCBLPXYmEPoB+gfb319Z39MwPzM/kU0dhlmiUI7rMBqEBt1Rcxw="
