version: '3.7'
services:
    build:
        build:
            context: .
            target: setup
        image: algorithmx-build
        volumes:
            - './dist:/app/dist'
            - './docs:/app/docs'
            - './coverage:/app/coverage'
        command: bash -c "
            npm run test
            && npm run build
            && npm run docs"
