name: build
on: [push]

jobs:
    app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build library and docs
              run: docker-compose up --build build

            - name: Codecov
              if: github.ref == 'refs/heads/master'
              uses: codecov/codecov-action@v1

            - name: Deploy docs
              if: github.ref == 'refs/heads/master'
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEPLOY_GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
              run: ./scripts/deploy-docs.sh

            - name: Deploy to NPM
              if: startsWith(github.ref, 'refs/tags/v')
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
